### ISSUE TITLE
Replace links to contact us with links to the volunteer form on the website

### ISSUE THREAD

**Issue by slarson** [openworm/openworm.github.io#114]
Currently it is too hard to find the [volunteer form](https://docs.google.com/spreadsheet/viewform?usp=drive_web&formkey=dC1CUDQtTV82MEJJcjY0NjdCcHpYdmc6MQ#gid=0), because you have to go to the [readthedocs](http://docs.openworm.org/en/latest/#contributing-to-openworm) and it is several clicks from the front page.

It would be better to add the volunteer form link to several of the hyper links on the website about getting involved and reach out to us.  After you fill out the form you get the invite to the Slack channel so even better.

* [Contact form](http://www.openworm.org/contacts.html) -- Make it the first block
* [Science page, social media section](http://www.openworm.org/science.html#social) -- Add it as the first item

**Comment by MichaelCurrie** [comment]
@slarson to make this issue accessible can you please specify exactly where on the website you would like the links added?  Thanks

**Comment by slarson** [comment]
Good call.

Actually I noticed that we have added a link to to the form at the bottom of the homepage.  That is a good start.  I'm updating the description now to be more specific.

**Comment by geekSiddharth** [comment]
On a related note.
The volunteer form seems to be a bit long to me. That might affect the conversion rate. 
And joining us on Slack doesn't implies that the person want to volunteer for OpenWorm. 

I think we should separate the volunteer form and slack invitation.

**Comment by slarson** [comment]
The downside of separating them is that we have people popping into slack
without any ability for our communty committee to know who they are beyond
name and therefore makes it hard to help them find the part of the project
they can help the most with.  We don't necessarily want a high conversion
rate into slack if people aren't willing to volunteer in some capacity-- so
its a tradeoff.  We have social media if folks just want info or to ask
simple questions--Having a mild hurdle of filling out a form to get to
slack I think is appropriate.

**Comment by geekSiddharth** [comment]
Valid point. 

Mentioning something like "We have social media if folks just want info or to ask
simple questions-mentioning " near volunteer form/Contact us block might prove useful.
