### ISSUE TITLE
Move slack notice up higher on the webpage

### ISSUE THREAD

**Issue by slarson** [openworm/openworm.github.io#120]

**Comment by geekSiddharth** [comment]
Move to?

**Comment by slarson** [comment]
How about just above "Open Science at its best"?

**Comment by arnab1896** [comment]
Dear devs,
just created a pull request --> https://github.com/openworm/openworm.github.io/pull/128

let me know if i have done it properly. :smile:

**Comment by slarson** [comment]
Closed by #128
