### ISSUE TITLE
Repositories page no longer working

### ISSUE THREAD

**Issue by slarson** [openworm/openworm.github.io#132]
http://openworm.org/repositories -- gear just keeps spinning

**Comment by gidili** [comment]
@slarson needs some styling love and we are missing a bunch of repos but it's working again, let me know if it's coming up for you (might need to clear cache) and if so let's close this

**Comment by slarson** [comment]
Just seeing this!  It works!  There are a few styling issues for sure but will close this for now.  Thank you!
