### ISSUE TITLE
Search box not functioning

### ISSUE THREAD

**Issue by pgleeson** [openworm/openworm.github.io#136]
Typing a word into the search box on http://docs.openworm.org & pressing return just gets the same page reloaded. 

Remove if not operational..?

**Comment by emilesilvis** [comment]
Seems like it might be fixed by upgrading RTD (https://github.com/rtfd/readthedocs.org/issues/141, https://github.com/rtfd/readthedocs.org/issues/1487).

**Comment by pgleeson** [comment]
Fixed now!
