### ISSUE TITLE
Add a page listing past successful GSoC projects

### ISSUE THREAD

**Issue by pgleeson** [openworm/openworm.github.io#140]
e.g. www.openworm.org/gsoc. 

Would be good for new applicants, for acknowledging (and thanking) the funder, and will be good if OpenWorm wants to be come a standalone organisation getting slots in GSoc in future...

Could be added/updated at http://openworm.org/supporters.html for now...

**Comment by pgleeson** [comment]
@balicea Could you possibly add the names of your current/previous GSoC students to the appropriate section in http://openworm.org/supporters.html? I think most of the recent students have been with your projects, but if you know of any others too... @slarson do you know of any others?

**Comment by balicea** [comment]
@pgleeson Added all the student I have been able to remember from 2017-2020. Also added our GSoD contributor (Casper DCL).

**Comment by balicea** [comment]
@pgleeson Also re-stylized the content, as there are now many more names than previous. Should be build a table structure for this, or leave it as a paragraph?

**Comment by pgleeson** [comment]
Thanks for that @balicea! Looks good to me as it is, but the next step might be to make a dedicated page for GSoC, perhaps with links to some of the repos the different students had worked on... Not super urgent, but good that we're giving more credit to gsoc and all the students that have done the work...

**Comment by pgleeson** [comment]
Replaced by #186

**Comment by Orthogonal-Research-Lab** [comment]
I can put the DevoWorm people from 2019 (?) on, let me confirm and add them via PR.
