### ISSUE TITLE
Modify donation buttons to allow for recurring donations

### ISSUE THREAD

**Issue by tarelli** [openworm/openworm.github.io#147]
- [ ] Add a checkbox (ticked by default) which will make the donations be recurrent (i.e. subscription) or not
- [ ] Update default amounts as in the example below provided by NeuroLinx
- [ ] Keep the same look and feel
- [ ] Update also the home page buttons
- [ ] Test

While the code below works it renders a dropdown and a Paypal subscribe button rather than having it looking like what we currently have now and also it doesn't offer the ability to tweak the type of donation, i.e. picking a custom amount and making it recurrent or not, etc.
```
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="JZKH5JYLGYG22">
<table>
<tr><td><input type="hidden" name="on0" value="Payment Options">Payment Options</td></tr><tr><td><select name="os0">
<option value="Option 1">Option 1 : $10.00 USD - monthly</option>
<option value="Option 2">Option 2 : $20.20 USD - monthly</option>
<option value="Option 3">Option 3 : $50.00 USD - monthly</option>
<option value="Option 4">Option 4 : $100.00 USD - monthly</option>
<option value="Option 5">Option 5 : $250.00 USD - monthly</option>
<option value="Option 6">Option 6 : $500.00 USD - monthly</option>
<option value="Option 7">Option 7 : $1,000.00 USD - monthly</option>
</select> </td></tr>
</table>
<input type="hidden" name="currency_code" value="USD">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>
```

**Comment by gidili** [comment]
I think we should explore creating a patreon account for the openworm foundation, there's a specific option for [non-profits](https://www.patreon.com/c/nonprofits). If not patreon some similar platform.

**Comment by pgleeson** [comment]
Done with link to OpenCollective
