### ISSUE TITLE
Remove or replace obsolete items from the banner carousel in homepage

### ISSUE THREAD

**Issue by gidili** [openworm/openworm.github.io#155]
- [ ] Wormsim has been discountinued and is now offline after 4+ years of support - we need to remove that entry from the homepage banner. 
- [ ] The optimal neuron stuff also should be removed and ideally replaced with something else more current  

@pgleeson any ideas of more active subprojects we could replace those 2 with?

**Comment by gidili** [comment]
ChannelWorm is a candidate of something to add to the carousel, see issue here --> https://github.com/openworm/openworm.github.io/issues/131

This is an easy pick if anybody wants to do it, just need a nice background image and the rest is trivial.

**Comment by PaulinaQuintero** [comment]
I can look this

**Comment by gidili** [comment]
Hi @PaulinaQuintero - yes thanks, you can take a stab at this as soon as we have a consensus. Will remove the "needs-definition" label and ping you when this is ready! 🙏 

@pgleeson what do you think?

**Comment by pgleeson** [comment]
Thanks for the offer of help @PaulinaQuintero 

Personally I'd recommend keeping WormSim there for the time being (to demonstrate a concrete outcome of the project), maybe just keeping the link to the YouTube video, and removing the link to wormsim.org. The wording could be updated to: **Enter the worm!**
Thanks to our Kickstarter backers we developed WormSim, an interactive way to play with the worm in your browser! 

I agree optimal neuron can be removed.

The link on the NeuroML Connectome page can be replaced with http://www.opensourcebrain.org/projects/c302/repository/revisions/master/show/examples?explorer=https%253A%252F%252Fraw.githubusercontent.com%252Fopenworm%252Fc302%252Fmaster%252Fexamples%252Fc302_D_Full.net.nml

**Comment by PaulinaQuintero** [comment]
I did a pull request with the changes!
