### ISSUE TITLE
Add a prominent link to the new "readthedocs" docs somewhere on the site

### ISSUE THREAD

**Issue by gidili** [openworm/openworm.github.io#40]
We need a prominent link to the docs: http://docs.openworm.org/en/latest/

We have links in the text here and there but this deserves to be more visible. Top bar is _very_ crowded at the moment, causing the menu to collapse into the mobile version if the window width isn't enough. We can add to the footer for now but ideally this should go on the top bar.

**Comment by pgleeson** [comment]
The docs at readthedocs are linked to in multiple locations now.
