### ISSUE TITLE
Update downloads page

### ISSUE THREAD

**Issue by slarson** [openworm/openworm.github.io#59]
Currently many of the [links to downloads](www.openworm.org/downloads.html) are stale!  Any suggestions for keeping these in sync more automatically also welcome!

**Comment by slarson** [comment]
Links aren't broken, but we could put a lot more content up there.  Next step is to identify what it all is and post it.

**Comment by pgleeson** [comment]
Fixed with https://github.com/openworm/openworm.github.io/pull/154
