### ISSUE TITLE
Use templates for header and footer

### ISSUE THREAD

**Issue by tarelli** [openworm/openworm.github.io#93]
The website should use a template engine. At the moment header and footer is duplicated in every HTML file. Anyone with some spare time?

**Comment by cheelee** [comment]
Hey I think this could be made into a beginner issue.

**Comment by shubhsingh594** [comment]
can i try my hand at this ?

**Comment by tarelli** [comment]
@shubhsingh594 sure, that would be rather useful! Just fork the repo and
create a PR when ready. What templating library do you have experience
with? Thanks!

**Comment by shubhsingh594** [comment]
I was thinking of using jinja , its a python based tempting engine.

**Comment by tarelli** [comment]
Cool, Handlerbars should do the job, as a reminder the current OpenWorm website uses Google App Engine Java (https://cloud.google.com/appengine/docs/standard/java/).

**Comment by slarson** [comment]
Please note that Mustache.js is [already being used on the People page](https://github.com/openworm/org.openworm.website/blob/master/war/people.html#L59).... we could expand this to headers and footers

**Comment by MichaelCurrie** [comment]
Possibly related: https://github.com/openworm/org.openworm.website/pull/110

**Comment by notsambeck** [comment]
Hey all, quick status update:
I'm still working on this, making progress. I think something like [pjax](https://github.com/defunkt/jquery-pjax) is the way to go. Seems more maintainable and straightforward than faking 'navigation' in a single-page type design.

- Real navigation with existing URLs
- All browser functionality works (links, forward/back)
- CSS and JS load once per site visit
- If pjax fails, the page loads normally

Optionally, server can be configured to respond to pjax requests with only the new content for a given page. This would speed things up some, but is probably less critical than the CSS/JS reuse.

Anyway, this is still going slower than I expected but I'm working on it, will have time over the next week. Let me know if this sounds like a bad plan and I can reconsider!

**Comment by MichaelCurrie** [comment]
Nothing specific to add but thank you for what looks like some comprehensive ongoing work here @notsambeck.

**Comment by tarelli** [comment]
@notsambeck sounds good, thanks for the update, give us a shout if you need to discuss anything! :)

**Comment by pgleeson** [comment]
Currently
https://github.com/openworm/openworm.github.io/blob/master/header-content.html and
https://github.com/openworm/openworm.github.io/blob/master/footer-content.html are used for header/footer, so this is no longer an issue (though the overall structure of the website could be overhauled, but that's a bigger issue)
