### ISSUE TITLE
Update "Events" page on openworm.org

### ISSUE THREAD

**Issue by balicea** [openworm/openworm.github.io#99]
Add more recent meetings (e.g. International C. elegans Meeting) with links.

**Comment by MichaelCurrie** [comment]
**Page location:** 
http://www.openworm.org/events.html
https://github.com/openworm/org.openworm.website/blob/master/war/events.html

**Updates to make**
https://www.youtube.com/watch?v=RY2-0-QsuTE&utm_source=OpenWorm+Newsletter&utm_campaign=19a5d33d30-OpenWorm_Newsletter6_2_2016&utm_medium=email&utm_term=0_abed5b9598-19a5d33d30-60054665

http://us12.campaign-archive1.com/?u=eeeaea04e12e1bae5555780ec&id=0c4e016cec&e=22520eef7d

http://us12.campaign-archive1.com/?u=eeeaea04e12e1bae5555780ec&id=19a5d33d30&e=22520eef7d

**Formatting changes**
Consider changing the format from this plain list:

![image](https://user-images.githubusercontent.com/5267078/27522189-f9147642-59d8-11e7-85ab-551b96efa7aa.png)

to this bootstrap list:

![image](https://user-images.githubusercontent.com/5267078/27522225-3006ab48-59d9-11e7-97a3-760b6fef4849.png)

https://bootsnipp.com/snippets/featured/event-list

**Comment by pgleeson** [comment]
This issue has more links: #139

**Comment by pgleeson** [comment]
@gidili Better to stick with the original colours for the list or OW colour scheme here?

<img width="1189" alt="Screenshot 2020-06-02 at 12 38 39" src="https://user-images.githubusercontent.com/1556687/83516260-a9f75b80-a4ce-11ea-9b2b-a0dc97bd8b73.png">



<img width="1222" alt="Screenshot 2020-06-02 at 12 38 10" src="https://user-images.githubusercontent.com/1556687/83516208-94823180-a4ce-11ea-908b-c1e57d77106a.png">


https://github.com/openworm/openworm.github.io/blob/development/css/events_css.css#L22

**Comment by gidili** [comment]
@pgleeson the OW colour scheme is more "orthodox" but the contrast with the pink and purple (which is, btw, my favourite colour 👾) has a "je ne sais quois" that makes it visually interesting and has more punch to it 🤔

**Comment by pgleeson** [comment]
Purple & pink it is so!

**Comment by pgleeson** [comment]
Closed with https://github.com/openworm/openworm.github.io/pull/154
